"""account_pks added to holdings and orders

Revision ID: 636be87ebab5
Revises: 6193f9f47bd4
Create Date: 2018-09-20 18:56:09.808216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636be87ebab5'
down_revision = '6193f9f47bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('account_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'holdings', 'accounts', ['account_pk'], ['id'])
    op.add_column('orders', sa.Column('account_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'accounts', ['account_pk'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'account_pk')
    op.drop_constraint(None, 'holdings', type_='foreignkey')
    op.drop_column('holdings', 'account_pk')
    # ### end Alembic commands ###
